name: SonarQube Cloud

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-22.04  # Using Ubuntu 22.04 for the build and test job

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full clone for better analysis

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'  # Use 'temurin' as the JDK distribution

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Cache SonarQube Cloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Run tests with Maven
        run: mvn test --file pom.xml

#      - name: Build and analyze with SonarQube
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed for GitHub PR information
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=jhonatademuner_roman-converter
